name: Main
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Download Screenshots
        uses: actions/download-artifact@v2
        with:
          name: screenshots
          path: ./test/__screenshots__
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting --public dist
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}